#!/usr/bin/env bash
# Installs Nginx with the following configurations:
## server
## Nginx should be listening on port 80
## When querying Nginx at its root / with a GET request (requesting a page)\
### using curl, it must return a page that contains the string Hello World!
## As an answer file, write a Bash script that configures a new Ubuntu machine\
### to respect above requirements (this script will be run on the server itself)
## You can’t use systemctl for restarting nginx

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
