#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# but for the 9th iteration, displays Holberton School and then Hi on a new line.
c=0
while [ $c -lt 10 ]
do
	
	echo "Best School"
	if [ $c -eq 8 ]
	then echo "Hi"	
	fi
	((c++))
done
