#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#but displays "bad luck" for the 4th loop iteration
#and "good luck" for the 8th loop iteration
c=0
while [ $c -lt 10 ]
do
	if  [ $c -eq 3 ]
	then echo  "bad luck"
	
	elif [ $c -eq 7 ]

	then echo "good luck"

	else
		echo "Best School"
	fi
	((c++))
	
done
